#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Objectionary.com
# SPDX-License-Identifier: MIT

set -e -o pipefail

dir=.zenodo
zip=zenodo.zip

rm -rf "${dir}"

mkdir "${dir}"

function log {
    ${PRINTF} '%s\n\n' "$@" >> "${dir}/README.txt"
}

log "This archive contains the artifact for the paper."
log "It was automatically generated by the Makefile in the objectionary/hone-paper GitHub repository."

cp arXiv.zip "${dir}"
log "The arXiv.zip contains LaTeX sources of the paper."

jars=(
    "org/eolang/hone-maven-plugin/${HONE_VERSION}/hone-maven-plugin-${HONE_VERSION}.jar"
    "org/eolang/hone-maven-plugin/${JEO_VERSION}/jeo-maven-plugin-${JEO_VERSION}.jar"
)
for jar in "${jars[@]}" ; do
    url="https://repo1.maven.org/maven2/${jar}"
    n=$(basename "${jar}")
    curl -s -o "${dir}/${n}" "${url}"
    log "The ${n} file is a released version of the product, from Maven Central: ${url}."
done

while IFS= read -r f; do
    mkdir -p "${dir}/$(dirname "${f}")"
    cp "${f}" "${dir}/${f}"
done < <(${FIND} tables -name '*.csv' -o -name '*.out')
log "The tables/ directory contains raw data collected by the JMH."

products=(
    "objectionary/hone-maven-plugin:${HONE_VERSION}"
    "objectionary/jeo-maven-plugin:${JEO_VERSION}"
    "objectionary/phino:${PHINO_VERSION}"
    "objectionary/kafka:stable"
)

for ln in "${products[@]}" ; do
    repo=$(echo "${ln}" | cut -f1 -d ':')
    tag=$(echo "${ln}" | cut -f2 -d ':')
    d=$(echo "${repo}" | cut -f2 -d '/')
    git clone --depth=1 "https://github.com/${repo}" "${dir}/${d}"
    git "--git-dir=${dir}/${d}/.git" "--work-tree=${dir}/${d}" fetch --tags
    git "--git-dir=${dir}/${d}/.git" "--work-tree=${dir}/${d}" checkout "${tag}"
    rm -rf "${dir:?}/${d}/.git"
    cd "${dir}/${d}" && zip -qr "../${d}-${tag}.zip" ./* && cd ../..
    rm -rf "${dir:?}/${d}"
    log "The ${d}/ directory contains source code of the ${repo} GitHub repository (tag '${tag}')."
done

rm -f "${zip}"
cd "${dir}" && zip -qr "../${zip}" ./* && cd ..
