# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Objectionary.com
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: make
'on':
  push:
    branches:
      - master
concurrency:
  group: make-${{ github.ref }}
  cancel-in-progress: true
jobs:
  make:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
      - run: gem install texsc texqc
      - run: |
          sudo apt-get update
          sudo apt-get install --yes xpdf
      - run: |
          sudo apt-get update
          sudo apt-get install --yes aspell
      - uses: zauguin/install-texlive@v4.0.0
        with:
          packages: latexmk multirow threeparttable lineno xurl scheme-basic tikzmark geometry xcolor microtype etoolbox acmart adjustbox algorithmicx algpseudocodex anyfontsize babel-russian bbold biblatex booktabs bussproofs cancel caption catchfile changepage cjk cleveref clicks cm-super cmap comment crumbs csquotes currfile cyrillic datetime debate docshots doi enumitem environ eolang everyshi fdsymbol ffcode float fmtcount fontsize footmisc framed fvextra href-ul hyperxmp hyphen-russian iexec ifmtarg ifoddpage lastpage lh libertine listings listingsutf8 makecell mathtools mdframed microtype naive-ebnf ncctools needspace paralist pdfcol pgf ppt-slides preprint semantic setspace stmaryrd svg textcase textpos tikzfill titling to-be-determined totpages transparent trimspaces upquote wrapfig xstring zref
          texlive_version: 2025
      - uses: sdkman/sdkman-action@main
        with:
          candidate: java
          version: 24.0.2-zulu
      - run: make paper.pdf REPEAT=2 VENDORS=2 NUMBERS=10 WARMUPS=2 ITERATIONS=5 || ( tail -500 log.txt; exit 1 )
      - run: |
          mkdir gh-pages
          cp paper.pdf gh-pages
      - uses: JamesIves/github-pages-deploy-action@v4.7.4
        with:
          branch: gh-pages
          folder: gh-pages
          clean: false
        if: github.ref == 'refs/heads/master'
